/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CampaignContract } from "./CampaignContract";
export type { DonationContract } from "./DonationContract";
export type { GIVToken } from "./GIVToken";
export type { TransparencyContract } from "./TransparencyContract";
