/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace TransparencyContract {
  export type DonationRecordStruct = {
    campaignId: BigNumberish;
    donor: AddressLike;
    amount: BigNumberish;
    timestamp: BigNumberish;
  };

  export type DonationRecordStructOutput = [
    campaignId: bigint,
    donor: string,
    amount: bigint,
    timestamp: bigint
  ] & { campaignId: bigint; donor: string; amount: bigint; timestamp: bigint };

  export type RefundRecordStruct = {
    campaignId: BigNumberish;
    donor: AddressLike;
    amount: BigNumberish;
    timestamp: BigNumberish;
  };

  export type RefundRecordStructOutput = [
    campaignId: bigint,
    donor: string,
    amount: bigint,
    timestamp: bigint
  ] & { campaignId: bigint; donor: string; amount: bigint; timestamp: bigint };

  export type ReleaseRecordStruct = {
    campaignId: BigNumberish;
    charity: AddressLike;
    amount: BigNumberish;
    timestamp: BigNumberish;
  };

  export type ReleaseRecordStructOutput = [
    campaignId: bigint,
    charity: string,
    amount: bigint,
    timestamp: bigint
  ] & {
    campaignId: bigint;
    charity: string;
    amount: bigint;
    timestamp: bigint;
  };
}

export interface TransparencyContractInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "donationLogs"
      | "getDonationCount"
      | "getDonationLogs"
      | "getRefundLogs"
      | "getReleaseLogs"
      | "logDonation"
      | "logRefund"
      | "logRelease"
      | "refundLogs"
      | "releaseLogs"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DonationReceived"
      | "FundsReleased"
      | "RefundIssued"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "donationLogs",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDonationCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDonationLogs",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRefundLogs",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getReleaseLogs",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "logDonation",
    values: [BigNumberish, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "logRefund",
    values: [BigNumberish, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "logRelease",
    values: [BigNumberish, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "refundLogs",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "releaseLogs",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "donationLogs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDonationCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDonationLogs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRefundLogs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReleaseLogs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "logDonation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "logRefund", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "logRelease", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "refundLogs", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "releaseLogs",
    data: BytesLike
  ): Result;
}

export namespace DonationReceivedEvent {
  export type InputTuple = [
    campaignId: BigNumberish,
    donor: AddressLike,
    amount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    campaignId: bigint,
    donor: string,
    amount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    campaignId: bigint;
    donor: string;
    amount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FundsReleasedEvent {
  export type InputTuple = [
    campaignId: BigNumberish,
    charity: AddressLike,
    amount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    campaignId: bigint,
    charity: string,
    amount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    campaignId: bigint;
    charity: string;
    amount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RefundIssuedEvent {
  export type InputTuple = [
    campaignId: BigNumberish,
    donor: AddressLike,
    amount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    campaignId: bigint,
    donor: string,
    amount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    campaignId: bigint;
    donor: string;
    amount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TransparencyContract extends BaseContract {
  connect(runner?: ContractRunner | null): TransparencyContract;
  waitForDeployment(): Promise<this>;

  interface: TransparencyContractInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  donationLogs: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, bigint] & {
        campaignId: bigint;
        donor: string;
        amount: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  getDonationCount: TypedContractMethod<[], [bigint], "view">;

  getDonationLogs: TypedContractMethod<
    [],
    [TransparencyContract.DonationRecordStructOutput[]],
    "view"
  >;

  getRefundLogs: TypedContractMethod<
    [],
    [TransparencyContract.RefundRecordStructOutput[]],
    "view"
  >;

  getReleaseLogs: TypedContractMethod<
    [],
    [TransparencyContract.ReleaseRecordStructOutput[]],
    "view"
  >;

  logDonation: TypedContractMethod<
    [campaignId: BigNumberish, donor: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  logRefund: TypedContractMethod<
    [campaignId: BigNumberish, donor: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  logRelease: TypedContractMethod<
    [campaignId: BigNumberish, charity: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  refundLogs: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, bigint] & {
        campaignId: bigint;
        donor: string;
        amount: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  releaseLogs: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, bigint] & {
        campaignId: bigint;
        charity: string;
        amount: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "donationLogs"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, bigint] & {
        campaignId: bigint;
        donor: string;
        amount: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getDonationCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getDonationLogs"
  ): TypedContractMethod<
    [],
    [TransparencyContract.DonationRecordStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRefundLogs"
  ): TypedContractMethod<
    [],
    [TransparencyContract.RefundRecordStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getReleaseLogs"
  ): TypedContractMethod<
    [],
    [TransparencyContract.ReleaseRecordStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "logDonation"
  ): TypedContractMethod<
    [campaignId: BigNumberish, donor: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "logRefund"
  ): TypedContractMethod<
    [campaignId: BigNumberish, donor: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "logRelease"
  ): TypedContractMethod<
    [campaignId: BigNumberish, charity: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "refundLogs"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, bigint] & {
        campaignId: bigint;
        donor: string;
        amount: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "releaseLogs"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, bigint] & {
        campaignId: bigint;
        charity: string;
        amount: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  getEvent(
    key: "DonationReceived"
  ): TypedContractEvent<
    DonationReceivedEvent.InputTuple,
    DonationReceivedEvent.OutputTuple,
    DonationReceivedEvent.OutputObject
  >;
  getEvent(
    key: "FundsReleased"
  ): TypedContractEvent<
    FundsReleasedEvent.InputTuple,
    FundsReleasedEvent.OutputTuple,
    FundsReleasedEvent.OutputObject
  >;
  getEvent(
    key: "RefundIssued"
  ): TypedContractEvent<
    RefundIssuedEvent.InputTuple,
    RefundIssuedEvent.OutputTuple,
    RefundIssuedEvent.OutputObject
  >;

  filters: {
    "DonationReceived(uint256,address,uint256,uint256)": TypedContractEvent<
      DonationReceivedEvent.InputTuple,
      DonationReceivedEvent.OutputTuple,
      DonationReceivedEvent.OutputObject
    >;
    DonationReceived: TypedContractEvent<
      DonationReceivedEvent.InputTuple,
      DonationReceivedEvent.OutputTuple,
      DonationReceivedEvent.OutputObject
    >;

    "FundsReleased(uint256,address,uint256,uint256)": TypedContractEvent<
      FundsReleasedEvent.InputTuple,
      FundsReleasedEvent.OutputTuple,
      FundsReleasedEvent.OutputObject
    >;
    FundsReleased: TypedContractEvent<
      FundsReleasedEvent.InputTuple,
      FundsReleasedEvent.OutputTuple,
      FundsReleasedEvent.OutputObject
    >;

    "RefundIssued(uint256,address,uint256,uint256)": TypedContractEvent<
      RefundIssuedEvent.InputTuple,
      RefundIssuedEvent.OutputTuple,
      RefundIssuedEvent.OutputObject
    >;
    RefundIssued: TypedContractEvent<
      RefundIssuedEvent.InputTuple,
      RefundIssuedEvent.OutputTuple,
      RefundIssuedEvent.OutputObject
    >;
  };
}
